# Generated by Django 5.2.5 on 2025-08-20 00:34

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_images/', validators=[management.models.validate_image_size])),
                ('high_school', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('master', models.CharField(blank=True, max_length=200, null=True)),
                ('other_education', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name_ko', models.CharField(max_length=100, verbose_name='Guardian Name (Korean)')),
                ('guardian_name_uz', models.CharField(max_length=100, verbose_name='Guardian Name (Uzbek)')),
                ('guardian_telephone', models.CharField(max_length=20)),
                ('guardian_relationship', models.CharField(choices=[('F', 'Father'), ('M', 'Mother')], max_length=1)),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Student ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name_ko', models.CharField(max_length=200, verbose_name='Document Name (Korean)')),
                ('document_name_uz', models.CharField(max_length=200, verbose_name='Document Name (Uzbek)')),
                ('file', models.FileField(upload_to='student_documents/', validators=[management.models.validate_pdf_file, management.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='management.student')),
            ],
            options={
                'verbose_name': 'Attached Document',
                'verbose_name_plural': 'Attached Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
