# Generated by Django 5.2.5 on 2025-08-20 00:56

import django.db.models.deletion
import management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('graduate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Graduate')),
                ('position', models.CharField(choices=[('Teacher', 'Teacher'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Director', 'Director'), ('Other', 'Other')], max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Work', 'Work'), ('End', 'End'), ('Rest', 'Rest')], default='Work', max_length=10, verbose_name='Sale')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employee_images/', validators=[management.validators.validate_image_size])),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('years', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('representative_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('position_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contract', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_domain', models.CharField(max_length=100, unique=True, verbose_name='Subdomain')),
                ('agreement_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[management.validators.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name_ko', models.CharField(max_length=200, verbose_name='Document Name (Korean)')),
                ('document_name_uz', models.CharField(max_length=200, verbose_name='Document Name (Uzbek)')),
                ('file', models.FileField(upload_to='employee_documents/', validators=[management.validators.validate_pdf_file, management.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='management.employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
