# Generated by Django 5.0.2 on 2025-08-21 18:16

import django.db.models.deletion
import management.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('type', models.CharField(choices=[('language', 'Language'), ('aboard', 'Aboard'), ('industry', 'Industry'), ('public', 'Public'), ('hospital', 'Hospital'), ('other', 'Other')], max_length=100, verbose_name='Type')),
                ('nationality', models.CharField(choices=[('uzbek', 'Uzbek'), ('korean', 'Korean'), ('other', 'Other')], max_length=100, verbose_name='Nationality')),
                ('representative_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('representative_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('position_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('agreement_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[management.validators.validate_image_size])),
            ],
        ),
        migrations.RemoveField(
            model_name='university',
            name='sub_domain',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Work', 'Work'), ('End', 'End'), ('Rest', 'Rest')], default='Work', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='university',
            name='contract',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='grade',
            field=models.CharField(blank=True, choices=[('best', 'Best'), ('excellent', 'Excellent'), ('average', 'Average'), ('low', 'Low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='years',
            field=models.CharField(blank=True, choices=[('2', '2 years'), ('4', '4 years')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CareerCounsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Counsel Date')),
                ('details_uz', models.TextField(blank=True, null=True, verbose_name='Details (Uzbek)')),
                ('details_ko', models.TextField(blank=True, null=True, verbose_name='Details (Korean)')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsels', to='management.career')),
            ],
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title_uz', models.CharField(max_length=100, verbose_name='Work Title (Uzbek)')),
                ('work_title_ko', models.CharField(max_length=100, verbose_name='Work Title (Korean)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('region_uz', models.CharField(max_length=100, verbose_name='Region (Uzbek)')),
                ('region_ko', models.CharField(max_length=100, verbose_name='Region (Korean)')),
                ('visa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visa')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='management.career')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('intermediate', 'Intermediate'), ('high', 'High')], max_length=100, verbose_name='Level')),
                ('lecture', models.CharField(choices=[('topik', 'TOPIK'), ('aboard', 'Aboard'), ('nurse', 'Nurse'), ('it', 'IT'), ('others', 'Others')], max_length=100, verbose_name='Lecture')),
                ('group', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Group')),
                ('opening_date', models.DateField(verbose_name='Opening date')),
                ('period', models.IntegerField(verbose_name='Period (in months)')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tuition Fee')),
                ('textbook_first', models.CharField(blank=True, max_length=200, null=True, verbose_name='Textbook 1')),
                ('textbook_second', models.CharField(blank=True, max_length=200, null=True, verbose_name='Textbook 2')),
                ('classroom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classroom')),
                ('teacher_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_first', to='management.employee')),
                ('teacher_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_second', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_payments', to='management.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(choices=[(2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], verbose_name='Years')),
                ('kind', models.CharField(choices=[('language', 'Language'), ('collegue', 'Collegue'), ('university', 'University'), ('graduate', 'Graduate')], max_length=50, verbose_name='Kind of Entrance')),
                ('order', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('spring', 'Spring'), ('winter', 'Winter')], max_length=50, verbose_name='Order')),
                ('from_date', models.DateField(verbose_name='Period from')),
                ('to_date', models.DateField(verbose_name='Period to')),
                ('contract_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract No')),
                ('state', models.CharField(choices=[('end', 'End'), ('now', 'Now'), ('after', 'After')], max_length=50, verbose_name='State')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='management.university')),
            ],
        ),
        migrations.CreateModel(
            name='EnteranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name_ko', models.CharField(max_length=200, verbose_name='Document Name (Korean)')),
                ('document_name_uz', models.CharField(max_length=200, verbose_name='Document Name (Uzbek)')),
                ('file', models.FileField(upload_to='student_documents/', validators=[management.validators.validate_pdf_file, management.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='management.enterance')),
            ],
            options={
                'verbose_name': 'Attached Document',
                'verbose_name_plural': 'Attached Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('enterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_payments', to='management.enterance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Do'), (2, 'Undo'), (3, 'End')], default=1)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='management.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='management.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnteranceStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract No')),
                ('bonus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bonus')),
                ('state', models.IntegerField(choices=[(1, 'Go'), (2, 'Pass'), (3, 'NP')], verbose_name='State')),
                ('recommend', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommendation')),
                ('enterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='management.enterance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterance_registrations', to='management.student')),
            ],
            options={
                'verbose_name': 'Entrance Student Registration',
                'verbose_name_plural': 'Entrance Student Registrations',
                'unique_together': {('enterance', 'student')},
            },
        ),
        migrations.CreateModel(
            name='OrganManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('manager_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to='management.organ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organ Manager',
                'verbose_name_plural': 'Organ Managers',
                'unique_together': {('organ', 'manager_id')},
            },
        ),
        migrations.CreateModel(
            name='UniversityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('manager_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='management.university')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Manager',
                'verbose_name_plural': 'University Managers',
                'unique_together': {('university', 'manager_id')},
            },
        ),
    ]
