# Generated by Django 5.0.2 on 2025-08-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_career_organ_remove_university_sub_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(default=list, help_text="List of days: ['monday', 'tuesday', etc.]", verbose_name='Days of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='management.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Class Timetable',
                'verbose_name_plural': 'Class Timetables',
                'ordering': ['start_time'],
            },
        ),
    ]
