# Generated by Django 5.0.2 on 2025-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_classtimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='days',
            field=models.CharField(choices=[('monday', '월요일 / Душанба'), ('tuesday', '화요일 / Сешанба'), ('wednesday', '수요일 / Чоршанба'), ('thursday', '목요일 / Пайшанба'), ('friday', '금요일 / Жума'), ('saturday', '토요일 / Шанба'), ('sunday', '일요일 / Якшанба')], max_length=100, verbose_name='Days of the Week'),
        ),
    ]
