# Generated by Django 5.0.2 on 2025-08-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_classtimetable_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Do'), (2, 'Undo'), (3, 'End')], default=1)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='management.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to='management.student')),
            ],
            options={
                'unique_together': {('student', 'class_model')},
            },
        ),
    ]
