# Generated by Django 5.0.2 on 2025-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_classstudentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='current_month',
            field=models.IntegerField(default=1, verbose_name='Hozirgi oy'),
        ),
        migrations.AddField(
            model_name='classpayment',
            name='payment_month',
            field=models.IntegerField(default=1, verbose_name="To'lov oyi"),
        ),
    ]
