# Generated by Django 5.0.2 on 2025-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_class_current_month_classpayment_payment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymanager',
            name='manager_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
