# Generated by Django 5.0.2 on 2024-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='content',
            new_name='content_ko',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='fullname',
            new_name='fullname_ko',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experience',
            new_name='experience_ko',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='title_ko',
        ),
        migrations.RenameField(
            model_name='galleryitem',
            old_name='description',
            new_name='description_ko',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_ko',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_ko',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='full_name_ko',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='position',
            new_name='position_ko',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(default='title_uz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position_uz',
            field=models.CharField(default='title_uz', max_length=50),
            preserve_default=False,
        ),
    ]
