# Generated by Django 5.0.2 on 2024-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_content_aboutus_content_ko_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback/')),
                ('fullname_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ko', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
