# Generated by Django 5.0.2 on 2024-02-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='content_ko',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='email',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='fullname_ko',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='fullname_uz',
        ),
    ]
