# Generated by Django 5.0.2 on 2024-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_content_ko_aboutus_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_oquv', models.IntegerField(default=0)),
                ('jami_oquv', models.IntegerField(default=0)),
                ('oqituvchi', models.IntegerField(default=0)),
            ],
        ),
    ]
