# Generated by Django 5.0.2 on 2024-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='news_files/'),
        ),
    ]
