# Generated by Django 5.0.2 on 2025-08-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0004_career_organ_remove_university_sub_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Title in Uzbek')),
                ('title_ko', models.CharField(max_length=200, verbose_name='Title in Korean')),
                ('content_uz', models.TextField()),
                ('content_ko', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Title in Uzbek')),
                ('title_ko', models.CharField(max_length=200, verbose_name='Title in Korean')),
                ('content_uz', models.TextField()),
                ('content_ko', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='information_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.university')),
            ],
        ),
        migrations.CreateModel(
            name='InformationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='information_documents/')),
                ('document_uz', models.CharField(max_length=200, verbose_name='Document Title in Uzbek')),
                ('document_ko', models.CharField(max_length=200, verbose_name='Document Title in Korean')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='board.information')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Title in Uzbek')),
                ('title_ko', models.CharField(max_length=200, verbose_name='Title in Korean')),
                ('content_uz', models.TextField()),
                ('content_ko', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.university')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Title in Uzbek')),
                ('title_ko', models.CharField(max_length=200, verbose_name='Title in Korean')),
                ('content_uz', models.TextField()),
                ('content_ko', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.university')),
            ],
        ),
    ]
