# Generated by Django 5.0.2 on 2025-08-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('management', '0007_classstudentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.university'),
            preserve_default=False,
        ),
    ]
